config/routes.rb
Rails.application.routes.draw do
  resources :temperatures
  resources :rack_infos
  resources :package_in_outs
  resources :staff_infos
  resources :tickets
  resources :check_in_outs do
    member do
      get :check_in
      get :check_out
    end
  end
  resources :customer_staffs
  resources :customers
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates_presence_of :customer_code
  validates_presence_of :customer_name
  validates_presence_of :email
  validates_presence_of :phone_no
  validates_presence_of :address
  validates_presence_of :join_date
  validates_length_of :customer_code, :is =>5
  validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  validates_uniqueness_of :customer_code
  validates_uniqueness_of :customer_name

  self.primary_key = :customer_code
  has_many :customer_staffs, :class_name => CustomerStaff, :foreign_key => :customer_code
  has_many :tickets, :class_name => Ticket, :foreign_key => :customer_code
  has_many :rack_infos
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @q = Customer.ransack(params[:q])
    @customers = @q.result(distinct: true)
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customers = Customer.all
    @customer_staffs = CustomerStaff.all
    @rack_infos = RackInfo.all

    @staff_no = 1
    @col_count = 0
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:customer_code, :customer_name, :email, :phone_no, :address, :join_date)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_code %>
    <%= f.text_field :customer_code %>
  </div>

  <div class="field">
    <%= f.label :customer_name %>
    <%= f.text_field :customer_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone_no %>
    <%= f.text_field :phone_no %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :join_date %>
    <%= f.date_field :join_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-9">
      <div class="widget">
        <div class="widget-header">
          <h1><span class="glyphicon glyphicon-globe"></span><b> Companies List</b></h1>
        </div>
        <div class="widget-body">
          <table class="table table-hover">
            <thead>
            <tr>
              <th><%= sort_link(@q, :customer_code, 'Customer Code') %></th>
              <th><%= sort_link(@q, :customer_name, 'Customer Name') %></th>
              <th><%= sort_link(@q, :email, 'Email') %></th>
              <th><%= sort_link(@q, :phone_no, 'Phone no') %></th>
              <th><%= sort_link(@q, :address, 'Address') %></th>
              <th><%= sort_link(@q, :join_date, 'Join Date') %></th>
              <th colspan="3"></th>
            </tr>
            </thead>

            <tbody>
            <% @customers.each do |customer| %>
                <tr>
                  <td><%= customer.customer_code %></td>
                  <td><%= customer.customer_name %></td>
                  <td><%= customer.email %></td>
                  <td><%= customer.phone_no %></td>
                  <td><%= customer.address %></td>
                  <td><%= customer.join_date %></td>
                  <td><%= link_to 'Show', customer %></td>
                  <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
                  <td>
                    <%= button_to customer, method: :delete, id: 'trash_button', data: { confirm: 'Are you sure?' } do %>
                        <span class="glyphicon glyphicon-trash"></span>
                    <% end %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <br>
        <%= link_to 'New Customer', new_customer_path %>
      </div>
    </div>

    <div class="col-sm-3">
      <div class="widget">
        <div class="widget-header">
          <h3><b>Search Form</b></h3>
        </div>
        <div class="widget-body">
          <%= search_form_for @q, :class=>'form-group' do |f| %>
              <%= f.label :customer_code %>
              <%= f.search_field :customer_code_cont, :class=>'form-control' %>
              <%= f.label :customer_name %>
              <%= f.search_field :customer_name_cont, :class=>'form-control' %>
              <%= f.label :email %>
              <%= f.search_field :email_cont, :class=>'form-control' %>
              <%= f.label :phone_no %>
              <%= f.search_field :phone_no_cont, :class=>'form-control' %>
              <%= f.label :address %>
              <%= f.search_field :address_cont, :class=>'form-control' %>
              <%= f.label :join_date %>
              <%= f.date_field :join_date_cont, :class=>'form-control' %><br><br>
              <%= f.submit 'Search', class:"btn btn-outline-success", id: 'search_filter' %>
              <%= link_to 'Clear Filter', request.path, class:"btn btn-outline-warning", id: 'clear_filter' %>
          <% end %>
        </div>
      </div>

      <div class="widget">
        <div class="widget-header">
          <h3><b>Upload csv. file</b></h3>
        </div>
        <div class="widget-body"></div>
      </div>
    </div>
  </div>
</div>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<div class="container-fluid">
  <fieldset class="info_display">
    <legend><b>Customer Information</b></legend>
  <p>
    <strong>Customer code:</strong>
    <%= @customer.customer_code %>
  </p>

  <p>
    <strong>Customer name:</strong>
    <%= @customer.customer_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @customer.email %>
  </p>

  <p>
    <strong>Phone no:</strong>
    <%= @customer.phone_no %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @customer.address %>
  </p>

  <p>
    <strong>Join date:</strong>
    <%= @customer.join_date %>
  </p>

  <p>
    <%= link_to 'Edit', edit_customer_path(@customer) %>
    | <%= link_to 'Back', customers_path %>
  </p>
  </fieldset>

  <fieldset>
    <h3><b>Customer Staff List</b></h3>
    <% @customer_staffs.each do |customer_staff| %>
        <% if @customer.customer_code == customer_staff.customer_code %>
            <div class="col-sm-3">
              <div class="icon_staffs">
                <%= image_tag("Icon.jpg", size: "100x100", id: "icon") %>
                <div class="icon_staffs_text">
                  <b>Staff <%= @staff_no %>: </b><%= customer_staff.staff_first_name %> <%= customer_staff.staff_last_name %><br>
                  <b>Staff ID: </b><%= customer_staff.customer_staff_id %><br>
                  <b>Staff Email: </b><%= customer_staff.staff_email %><br>
                  <b>Staff Phone: </b><%= customer_staff.staff_phone %><br>
                  <%= link_to ' Edit', edit_customer_staff_path(customer_staff) %> |
                  <%= link_to ' Delete', customer_staff_path(customer_staff), method: :delete, data: {confirm: 'Are you sure?'} %>
                </div>
              </div>
            </div>
            <% @staff_no += 1 %>
        <% end %>
    <% end %>
  </fieldset>

  <hr>

  <fieldset>
    <h3><b>Customer Rack List</b></h3>
    <table class="table table-hover table-bordered">
      <thead>
      <tr>
        <th>Rack no</th>
        <th>Type</th>
        <th>Customer code</th>
        <th>Total unit</th>
        <th>Low unit</th>
        <th>Height unit</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @rack_infos.each do |rack_info| %>
          <% if @customer.customer_code == rack_info.customer_code %>
            <tr>
              <td><%= rack_info.rack_no %></td>
              <td><%= rack_info.tpye %></td>
              <td><%= rack_info.customer_code %></td>
              <td><%= rack_info.total_unit %></td>
              <td><%= rack_info.low_unit %></td>
              <td><%= rack_info.height_unit %></td>
              <td><%= link_to 'Show', rack_info %></td>
              <td><%= link_to 'Edit', edit_rack_info_path(rack_info) %></td>
              <td><%= link_to 'Destroy', rack_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
      <% end %>
      </tbody>
    </table>
  </fieldset>
</div>