config/routes.rb
Rails.application.routes.draw do
  resources :temperatures
  resources :rack_infos
  resources :package_in_outs
  resources :staff_infos
  resources :tickets
  resources :check_in_outs do
    member do
      get :check_in
      get :check_out
    end
  end
  resources :customer_staffs
  resources :customers
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/staff_info.rb
class StaffInfo < ApplicationRecord
  validates_presence_of :staff_id
  validates_presence_of :staff_first_name
  validates_presence_of :staff_last_name
  validates_presence_of :staff_email
  validates_presence_of :department
  validates_presence_of :staff_post
  validates_length_of :staff_id, :is =>6
  validates_numericality_of :staff_id, :only_integer => true
  validates_format_of :staff_email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  validates_uniqueness_of :staff_id
  validates_uniqueness_of :staff_email

  self.primary_key = :staff_id
  has_many :Ticket, :class_name => Ticket, :foreign_key => :staff_id
end

app/controllers/staff_infos_controller.rb
class StaffInfosController < ApplicationController
  before_action :set_staff_info, only: [:show, :edit, :update, :destroy]

  # GET /staff_infos
  # GET /staff_infos.json
  def index
    @staff_infos = StaffInfo.all
  end

  # GET /staff_infos/1
  # GET /staff_infos/1.json
  def show
  end

  # GET /staff_infos/new
  def new
    @staff_info = StaffInfo.new
  end

  # GET /staff_infos/1/edit
  def edit
  end

  # POST /staff_infos
  # POST /staff_infos.json
  def create
    @staff_info = StaffInfo.new(staff_info_params)

    respond_to do |format|
      if @staff_info.save
        format.html { redirect_to @staff_info, notice: 'Staff info was successfully created.' }
        format.json { render :show, status: :created, location: @staff_info }
      else
        format.html { render :new }
        format.json { render json: @staff_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staff_infos/1
  # PATCH/PUT /staff_infos/1.json
  def update
    respond_to do |format|
      if @staff_info.update(staff_info_params)
        format.html { redirect_to @staff_info, notice: 'Staff info was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff_info }
      else
        format.html { render :edit }
        format.json { render json: @staff_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staff_infos/1
  # DELETE /staff_infos/1.json
  def destroy
    @staff_info.destroy
    respond_to do |format|
      format.html { redirect_to staff_infos_url, notice: 'Staff info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff_info
      @staff_info = StaffInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_info_params
      params.require(:staff_info).permit(:staff_id, :staff_first_name, :staff_last_name, :staff_email, :staff_phone, :department, :staff_post)
    end
end

app/helpers/staff_infos_helper.rb
module StaffInfosHelper
end

app/views/staff_infos/_form.html.erb
<%= form_for(staff_info) do |f| %>
  <% if staff_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff_info.errors.count, "error") %> prohibited this staff_info from being saved:</h2>

      <ul>
      <% staff_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :staff_id %>
    <%= f.number_field :staff_id %>
  </div>

  <div class="field">
    <%= f.label :staff_first_name %>
    <%= f.text_field :staff_first_name %>
  </div>

  <div class="field">
    <%= f.label :staff_last_name %>
    <%= f.text_field :staff_last_name %>
  </div>

  <div class="field">
    <%= f.label :staff_email %>
    <%= f.text_field :staff_email %>
  </div>

  <div class="field">
    <%= f.label :staff_phone %>
    <%= f.text_field :staff_phone %>
  </div>

  <div class="field">
    <%= f.label :department %>
    <%= f.text_field :department %>
  </div>

  <div class="field">
    <%= f.label :staff_post %>
    <%= f.text_field :staff_post %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staff_infos/edit.html.erb
<h1>Editing Staff Info</h1>

<%= render 'form', staff_info: @staff_info %>

<%= link_to 'Show', @staff_info %> |
<%= link_to 'Back', staff_infos_path %>

app/views/staff_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staff Infos</h1>

<table>
  <thead>
    <tr>
      <th>Staff</th>
      <th>Staff first name</th>
      <th>Staff last name</th>
      <th>Staff email</th>
      <th>Staff phone</th>
      <th>Department</th>
      <th>Staff post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staff_infos.each do |staff_info| %>
      <tr>
        <td><%= staff_info.staff_id %></td>
        <td><%= staff_info.staff_first_name %></td>
        <td><%= staff_info.staff_last_name %></td>
        <td><%= staff_info.staff_email %></td>
        <td><%= staff_info.staff_phone %></td>
        <td><%= staff_info.department %></td>
        <td><%= staff_info.staff_post %></td>
        <td><%= link_to 'Show', staff_info %></td>
        <td><%= link_to 'Edit', edit_staff_info_path(staff_info) %></td>
        <td><%= link_to 'Destroy', staff_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff Info', new_staff_info_path %>

app/views/staff_infos/new.html.erb
<h1>New Staff Info</h1>

<%= render 'form', staff_info: @staff_info %>

<%= link_to 'Back', staff_infos_path %>

app/views/staff_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Staff:</strong>
  <%= @staff_info.staff_id %>
</p>

<p>
  <strong>Staff first name:</strong>
  <%= @staff_info.staff_first_name %>
</p>

<p>
  <strong>Staff last name:</strong>
  <%= @staff_info.staff_last_name %>
</p>

<p>
  <strong>Staff email:</strong>
  <%= @staff_info.staff_email %>
</p>

<p>
  <strong>Staff phone:</strong>
  <%= @staff_info.staff_phone %>
</p>

<p>
  <strong>Department:</strong>
  <%= @staff_info.department %>
</p>

<p>
  <strong>Staff post:</strong>
  <%= @staff_info.staff_post %>
</p>

<%= link_to 'Edit', edit_staff_info_path(@staff_info) %> |
<%= link_to 'Back', staff_infos_path %>