config/routes.rb
Rails.application.routes.draw do
  resources :temperatures
  resources :rack_infos
  resources :package_in_outs
  resources :staff_infos
  resources :tickets
  resources :check_in_outs do
    member do
      get :check_in
      get :check_out
    end
  end
  resources :customer_staffs
  resources :customers
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/rack_info.rb
class RackInfo < ApplicationRecord
  validates_presence_of :rack_no
  validates_presence_of :tpye
  validates_presence_of :customer_code
  validates_presence_of :total_unit
  validates_presence_of :low_unit
  validates_presence_of :height_unit
  validates_length_of :customer_code, :is =>5
  validates_numericality_of :total_unit, :only_integer => true
  validates_numericality_of :low_unit, :only_integer => true
  validates_numericality_of :height_unit, :only_integer => true

  belongs_to :customer, :class_name => Customer, :foreign_key => :customer_code
  has_many :temperatures, :foreign_key => :rack_no
  belongs_to :customer
end

app/controllers/rack_infos_controller.rb
class RackInfosController < ApplicationController
  before_action :set_rack_info, only: [:show, :edit, :update, :destroy]

  # GET /rack_infos
  # GET /rack_infos.json
  def index
    @rack_infos = RackInfo.all
  end

  # GET /rack_infos/1
  # GET /rack_infos/1.json
  def show
  end

  # GET /rack_infos/new
  def new
    @rack_info = RackInfo.new
  end

  # GET /rack_infos/1/edit
  def edit
  end

  # POST /rack_infos
  # POST /rack_infos.json
  def create
    @rack_info = RackInfo.new(rack_info_params)

    respond_to do |format|
      if @rack_info.save
        format.html { redirect_to @rack_info, notice: 'Rack info was successfully created.' }
        format.json { render :show, status: :created, location: @rack_info }
      else
        format.html { render :new }
        format.json { render json: @rack_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rack_infos/1
  # PATCH/PUT /rack_infos/1.json
  def update
    respond_to do |format|
      if @rack_info.update(rack_info_params)
        format.html { redirect_to @rack_info, notice: 'Rack info was successfully updated.' }
        format.json { render :show, status: :ok, location: @rack_info }
      else
        format.html { render :edit }
        format.json { render json: @rack_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rack_infos/1
  # DELETE /rack_infos/1.json
  def destroy
    @rack_info.destroy
    respond_to do |format|
      format.html { redirect_to rack_infos_url, notice: 'Rack info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rack_info
      @rack_info = RackInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rack_info_params
      params.require(:rack_info).permit(:rack_no, :tpye, :customer_code, :total_unit, :low_unit, :height_unit)
    end
end

app/helpers/rack_infos_helper.rb
module RackInfosHelper
end

app/views/rack_infos/_form.html.erb
<%= form_for(rack_info) do |f| %>
  <% if rack_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rack_info.errors.count, "error") %> prohibited this rack_info from being saved:</h2>

      <ul>
      <% rack_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rack_no %>
    <%= f.text_field :rack_no %>
  </div>

  <div class="field">
    <%= f.label :tpye %>
    <%= f.text_field :tpye %>
  </div>

  <div class="field">
    <%= f.label :customer_code %>
    <%= f.collection_select :customer_code, Customer.all, :id, :customer_code %>
  </div>

  <div class="field">
    <%= f.label :total_unit %>
    <%= f.number_field :total_unit %>
  </div>

  <div class="field">
    <%= f.label :low_unit %>
    <%= f.number_field :low_unit %>
  </div>

  <div class="field">
    <%= f.label :height_unit %>
    <%= f.number_field :height_unit %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rack_infos/edit.html.erb
<h1>Editing Rack Info</h1>

<%= render 'form', rack_info: @rack_info %>

<%= link_to 'Show', @rack_info %> |
<%= link_to 'Back', rack_infos_path %>

app/views/rack_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rack Infos</h1>

<table>
  <thead>
    <tr>
      <th>Rack no</th>
      <th>Tpye</th>
      <th>Customer code</th>
      <th>Total unit</th>
      <th>Low unit</th>
      <th>Height unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rack_infos.each do |rack_info| %>
      <tr>
        <td><%= rack_info.rack_no %></td>
        <td><%= rack_info.tpye %></td>
        <td><%= rack_info.customer_code %></td>
        <td><%= rack_info.total_unit %></td>
        <td><%= rack_info.low_unit %></td>
        <td><%= rack_info.height_unit %></td>
        <td><%= link_to 'Show', rack_info %></td>
        <td><%= link_to 'Edit', edit_rack_info_path(rack_info) %></td>
        <td><%= link_to 'Destroy', rack_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rack Info', new_rack_info_path %>

app/views/rack_infos/new.html.erb
<h1>New Rack Info</h1>

<%= render 'form', rack_info: @rack_info %>

<%= link_to 'Back', rack_infos_path %>

app/views/rack_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rack no:</strong>
  <%= @rack_info.rack_no %>
</p>

<p>
  <strong>Tpye:</strong>
  <%= @rack_info.tpye %>
</p>

<p>
  <strong>Customer code:</strong>
  <%= @rack_info.customer_code %>
</p>

<p>
  <strong>Total unit:</strong>
  <%= @rack_info.total_unit %>
</p>

<p>
  <strong>Low unit:</strong>
  <%= @rack_info.low_unit %>
</p>

<p>
  <strong>Height unit:</strong>
  <%= @rack_info.height_unit %>
</p>

<%= link_to 'Edit', edit_rack_info_path(@rack_info) %> |
<%= link_to 'Back', rack_infos_path %>