config/routes.rb
Rails.application.routes.draw do
  resources :temperatures
  resources :rack_infos
  resources :package_in_outs
  resources :staff_infos
  resources :tickets
  resources :check_in_outs do
    member do
      get :check_in
      get :check_out
    end
  end
  resources :customer_staffs
  resources :customers
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
    <li><%= link_to 'Companies List', customers_path %></li>
    <li><%= link_to 'Customer Staff List', customer_staffs_path %></li>
    <li><%= link_to 'Rack List', rack_infos_path %></li>
    <li><%= link_to 'Ticket System', tickets_path %></li>
    <li><%= link_to 'Check In List', check_in_outs_path %></li>
    <li><%= link_to 'Package In Out', package_in_outs_path %></li>
<% else %>
<% end %>
<% if user_signed_in? %>
    <% if current_user.try(:admin?) %>
        <li><%= link_to 'Users', users_path %></li>
    <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth_right.html.erb
<% if user_signed_in? %>
    <li><%= link_to Time.now.strftime("%H:%M - %d %B %Y - %A") %></li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hi, <%= current_user.email %><span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to edit_user_registration_path do %>
            <span class="glyphicon glyphicon-pencil"></span> Account Setting
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, :method=>'delete' do %>
          <span class="glyphicon glyphicon-log-out"></span> Sign Out
          <% end %>
        </li>
      </ul>
    </li>
<% else %>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <b><%= link_to 'Logo', root_path, class: 'navbar-brand' %></b>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/nav_links_for_auth_right' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise Roles" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise Roles" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>